// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrhogrAALzfHLB7ADY--vxVL3ZOC_K3kM',
    appId: '1:503730897487:android:06bce85c7b4f934277a03a',
    messagingSenderId: '503730897487',
    projectId: 'grocery-app-48185',
    storageBucket: 'grocery-app-48185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQrw49Of4YE3X14fCSx-yhmwc0lk7ntmA',
    appId: '1:503730897487:ios:0d4ba7422bcdf5b677a03a',
    messagingSenderId: '503730897487',
    projectId: 'grocery-app-48185',
    storageBucket: 'grocery-app-48185.appspot.com',
    androidClientId: '503730897487-gdi5m6g6eon0kk917l9k3vks10ppvf5k.apps.googleusercontent.com',
    iosClientId: '503730897487-dp1ts7m8ilfo19geqfvg0k354b7hven5.apps.googleusercontent.com',
    iosBundleId: 'com.shokhrukhbek.nectar',
  );
}
